# Generated by Django 5.0.14 on 2026-06-23 06:57

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="изображение",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "date",
                    models.DateField(
                        default=news.models.default_news_date, verbose_name="дата"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
