# Generated by Django 5.0.14 on 2026-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="адрес"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name="код"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="inn",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="ИНН"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("legal", "Юридическое лицо"),
                    ("individual", "Физическое лицо"),
                ],
                default="legal",
                max_length=16,
                verbose_name="тип",
            ),
        ),
    ]
