# Generated by Django 5.0.14 on 2026-06-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_address_user_code_user_inn_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Заполняется выгрузкой/синхронизацией с ERP.",
                max_digits=12,
                verbose_name="задолженность",
            ),
        ),
    ]
