# Generated by Django 5.0.14 on 2026-06-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_debt"),
        ("warehouses", "0005_alter_manager_options_manager_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Персональный менеджер покупателя.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="warehouses.manager",
                verbose_name="менеджер",
            ),
        ),
    ]
