# Generated by Django 5.0.14 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kpp",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="КПП"
            ),
        ),
    ]
