# Generated by Django 5.0.14 on 2026-07-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_kpp"),
        ("catalog", "0011_pricetype_productprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="price_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто = тип по умолчанию (Крупный ОПТ).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="catalog.pricetype",
                verbose_name="тип цены",
            ),
        ),
    ]
