# Generated by Django 5.0.14 on 2026-07-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_stock",
            field=models.BooleanField(
                default=False,
                help_text="Если выключено, покупатель видит «много / мало / только N» вместо точного количества.",
                verbose_name="показывать точный остаток",
            ),
        ),
    ]
