# Generated by Django 5.0.14 on 2026-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_show_stock"),
        ("warehouses", "0005_alter_manager_options_manager_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="warehouses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Склады, с которых покупатель заказывает сразу («его» склады). Остаток на других складах доступен с пометкой «Доставка 7 дней».",
                related_name="buyers",
                to="warehouses.warehouse",
            ),
        ),
    ]
