# Generated by Django 5.0.14 on 2026-07-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_user_warehouses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="код",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legal", "Юридическое лицо"),
                            ("individual", "Физическое лицо"),
                        ],
                        default="legal",
                        max_length=16,
                        verbose_name="тип",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="ИНН"
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="КПП"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="адрес"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Заполняется выгрузкой/синхронизацией с ERP.",
                        max_digits=12,
                        verbose_name="задолженность",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="название"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="телефон"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Личный кабинет, которому принадлежит компания.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "компания",
                "verbose_name_plural": "компании",
                "ordering": ["company_name", "code"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="название"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес доставки",
                "verbose_name_plural": "адреса доставки",
                "ordering": ["label", "address"],
            },
        ),
    ]
