# Generated by Django 5.0.14 on 2026-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_backfill_companies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="debt",
        ),
        migrations.RemoveField(
            model_name="user",
            name="inn",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kpp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
    ]
