# Generated by Django 5.0.14 on 2026-08-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_user_address_remove_user_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="free_delivery_min",
            field=models.DecimalField(
                decimal_places=2,
                default=3000,
                help_text="Заказ с доставкой ниже этой суммы оформить нельзя (самовывоз — без ограничения).",
                max_digits=12,
                verbose_name="мин. сумма для доставки",
            ),
        ),
    ]
