# Generated by Django 5.0.14 on 2026-08-19 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_user_free_delivery_min"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255, verbose_name="наименование компании"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="ИНН"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("processed", "Обработана"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="примечание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="получена"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="обработана"
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Аккаунт, созданный по этой заявке.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="созданный аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка на регистрацию",
                "verbose_name_plural": "заявки на регистрацию",
                "ordering": ["-created_at"],
            },
        ),
    ]
