# Generated by Django 5.0.14 on 2026-08-27 07:00

from django.conf import settings
from django.db import migrations, models


def copy_user_to_users(apps, schema_editor):
    """Preserve existing single-owner links when moving to many-to-many."""
    Company = apps.get_model("accounts", "Company")
    for company in Company.objects.exclude(user__isnull=True):
        company.users.add(company.user_id)


def copy_users_to_user(apps, schema_editor):
    """Reverse: keep the first linked user as the single FK owner."""
    Company = apps.get_model("accounts", "Company")
    for company in Company.objects.all():
        first = company.users.first()
        if first is not None:
            company.user = first
            company.save(update_fields=["user"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_registrationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Личные кабинеты, которым принадлежит компания (одну компанию можно назначить нескольким пользователям).",
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="аккаунты",
            ),
        ),
        migrations.RunPython(copy_user_to_users, copy_users_to_user),
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
    ]
