# Generated by Django 5.0.14 on 2026-09-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_company_users_m2m"),
        ("warehouses", "0006_warehouse_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="manager_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Если задано, пользователь входит как этот менеджер и видит в «Кабинете менеджера» своих клиентов.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account",
                to="warehouses.manager",
                verbose_name="профиль менеджера",
            ),
        ),
    ]
