# Generated by Django 5.0.14 on 2026-09-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_manager_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_view_sales",
            field=models.BooleanField(
                default=False,
                help_text="Разрешает просмотр раздела «Статистика продаж». Суперпользователям доступ открыт всегда.",
                verbose_name="доступ к статистике продаж",
            ),
        ),
    ]
