# Generated by Django 5.0.14 on 2026-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_user_can_view_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_order_supply",
            field=models.BooleanField(
                default=False,
                help_text="Разрешает раздел «Заказ поставщику» (пополнение запасов). Суперпользователям доступ открыт всегда.",
                verbose_name="доступ к заказу поставщикам",
            ),
        ),
    ]
