# Generated by Django 5.0.14 on 2026-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="изображение",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="текст")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Меньше — выше на странице.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
            ],
            options={
                "verbose_name": "блок «О компании»",
                "verbose_name_plural": "О компании (блоки)",
                "ordering": ["order", "id"],
            },
        ),
    ]
