# Generated by Django 5.0.14 on 2026-06-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutblock",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="заголовок"
            ),
        ),
    ]
