# Generated by Django 5.0.14 on 2026-06-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_aboutblock_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutblock",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Прикреплённый файл для скачивания (PDF, документ и т.д.).",
                null=True,
                upload_to="about/files/",
                verbose_name="файл",
            ),
        ),
    ]
