# Generated by Django 5.0.14 on 2026-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_aboutblock_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Общество с ограниченной ответственностью «Автомеханика-Сибирь»",
                        max_length=255,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        default="4205361870",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        default="420501001",
                        max_length=9,
                        verbose_name="КПП",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        default='ФИЛИАЛ ПАО "БАНК УРАЛСИБ" В Г. НОВОСИБИРСК',
                        max_length=255,
                        verbose_name="банк",
                    ),
                ),
                (
                    "bank_bic",
                    models.CharField(
                        blank=True,
                        default="045004725",
                        max_length=9,
                        verbose_name="БИК банка",
                    ),
                ),
                (
                    "corr_account",
                    models.CharField(
                        blank=True,
                        default="30101810400000000725",
                        max_length=20,
                        verbose_name="корр. счёт",
                    ),
                ),
                (
                    "settlement_account",
                    models.CharField(
                        blank=True,
                        default="40702810232210003010",
                        max_length=20,
                        verbose_name="расчётный счёт",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="650903, Россия, Кемеровская область, г. Кемерово, ул. Тухачевского 52В",
                        max_length=255,
                        verbose_name="адрес",
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True,
                        default="Моисеенко Константин Владимирович",
                        max_length=255,
                        verbose_name="директор",
                    ),
                ),
            ],
            options={
                "verbose_name": "реквизиты компании",
                "verbose_name_plural": "реквизиты компании",
            },
        ),
    ]
