# Generated by Django 5.0.14 on 2026-08-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_create_company_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutBrandBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Напр.: «Официальный дистрибьютор».",
                        max_length=80,
                        verbose_name="роль",
                    ),
                ),
                ("heading", models.CharField(max_length=160, verbose_name="заголовок")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
            ],
            options={
                "verbose_name": "блок бренда",
                "verbose_name_plural": "блоки брендов",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        blank=True,
                        default="О компании",
                        max_length=100,
                        verbose_name="надзаголовок",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Смазочные материалы для всей",
                        max_length=200,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "hero_title_accent",
                    models.CharField(
                        blank=True,
                        default="Сибири",
                        help_text="Последнее слово заголовка, выделенное акцентным цветом.",
                        max_length=100,
                        verbose_name="выделенное слово",
                    ),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        blank=True,
                        default="«Автомеханика-Сибирь» — один из ведущих поставщиков моторных, трансмиссионных и индустриальных масел, технических жидкостей и автохимии. Работаем с розничными, оптовыми и корпоративными клиентами с 2005 года.",
                        verbose_name="вводный текст",
                    ),
                ),
                (
                    "profile_eyebrow",
                    models.CharField(blank=True, default="Профиль", max_length=100),
                ),
                (
                    "profile_title",
                    models.CharField(blank=True, default="Кто мы", max_length=200),
                ),
                (
                    "profile_side_label",
                    models.CharField(
                        blank=True, default="Направление поставок", max_length=100
                    ),
                ),
                (
                    "profile_lead",
                    models.TextField(
                        blank=True,
                        default="Наше основное направление — поставка моторных, трансмиссионных и индустриальных масел, технических жидкостей, автохимии и сопутствующих товаров для легкового, коммерческого и промышленного транспорта.",
                    ),
                ),
                (
                    "profile_body",
                    models.TextField(
                        blank=True,
                        default="Собственная торговая команда позволяет оперативно взаимодействовать с клиентами, выстраивать долгосрочные партнёрские отношения и обеспечивать высокий уровень сервиса на каждом этапе сотрудничества — от подбора продукции до организации регулярных поставок.",
                    ),
                ),
                (
                    "profile_pull",
                    models.CharField(
                        blank=True,
                        default="Более 20 лет на рынке смазочных материалов Сибири.",
                        max_length=255,
                    ),
                ),
                (
                    "clients_eyebrow",
                    models.CharField(
                        blank=True, default="Клиенты и опыт", max_length=100
                    ),
                ),
                (
                    "clients_title",
                    models.CharField(
                        blank=True,
                        default="Работаем с федеральными сетями",
                        max_length=200,
                    ),
                ),
                (
                    "clients_body",
                    models.TextField(
                        blank=True,
                        default="Обладаем значительным опытом обслуживания крупных сетевых клиентов. Понимая специфику работы с федеральными и региональными сетями, строго соблюдаем требования к ассортименту, срокам поставки и стабильности товарного запаса. Участвуем в тендерах на поставку смазочных материалов для государственных и коммерческих предприятий.",
                    ),
                ),
                (
                    "brands_eyebrow",
                    models.CharField(blank=True, default="Наши бренды", max_length=100),
                ),
                (
                    "brands_title",
                    models.CharField(
                        blank=True, default="Что мы поставляем", max_length=200
                    ),
                ),
                (
                    "geo_eyebrow",
                    models.CharField(
                        blank=True, default="География поставок", max_length=100
                    ),
                ),
                (
                    "geo_title",
                    models.CharField(
                        blank=True, default="Три центра, пять регионов", max_length=200
                    ),
                ),
                (
                    "req_eyebrow",
                    models.CharField(blank=True, default="Реквизиты", max_length=100),
                ),
                (
                    "req_title",
                    models.CharField(
                        blank=True, default="Данные компании", max_length=200
                    ),
                ),
                (
                    "req_note",
                    models.TextField(
                        blank=True,
                        default="Полные реквизиты в формате PDF для оформления договоров и заявок.",
                    ),
                ),
            ],
            options={
                "verbose_name": "страница «О компании»",
                "verbose_name_plural": "страница «О компании»",
            },
        ),
        migrations.AddField(
            model_name="companydetails",
            name="card_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF с реквизитами для скачивания на странице «О компании».",
                null=True,
                upload_to="about/files/",
                verbose_name="карточка предприятия (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="companydetails",
            name="legal_form",
            field=models.CharField(
                blank=True,
                default="Общество с ограниченной ответственностью",
                max_length=255,
                verbose_name="организационно-правовая форма",
            ),
        ),
        migrations.AddField(
            model_name="companydetails",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="ООО «Автомеханика-Сибирь»",
                max_length=255,
                verbose_name="краткое наименование",
            ),
        ),
        migrations.CreateModel(
            name="AboutBrandChip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="название")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chips",
                        to="about.aboutbrandblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "бренд (плитка)",
                "verbose_name_plural": "бренды (плитки)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="метка")),
                ("value", models.CharField(max_length=60, verbose_name="значение")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="about.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "показатель (Hero)",
                "verbose_name_plural": "показатели (Hero)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClientTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=80, verbose_name="текст")),
                (
                    "accent",
                    models.BooleanField(
                        default=False,
                        help_text="Выделить акцентным цветом.",
                        verbose_name="акцент",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_tags",
                        to="about.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег клиента",
                "verbose_name_plural": "теги клиентов",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SupplyCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="город")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centers",
                        to="about.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "центр поставок",
                "verbose_name_plural": "центры поставок",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SupplyRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="регион")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="about.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "регион поставок",
                "verbose_name_plural": "регионы поставок",
                "ordering": ["order", "id"],
            },
        ),
    ]
