# Generated by Django 5.0.14 on 2026-08-15 11:13
from urllib.parse import quote

from django.db import migrations, models


def apply_tweaks(apps, schema_editor):
    ClientTag = apps.get_model("about", "ClientTag")
    AboutBrandChip = apps.get_model("about", "AboutBrandChip")
    Brand = apps.get_model("catalog", "Brand")

    # «Тендеры и госзакупки» is no longer highlighted.
    ClientTag.objects.filter(text="Тендеры и госзакупки").update(accent=False)

    # Link every brand chip: exact catalog brand -> its filter, otherwise a
    # catalog search by name. Skips chips a user already gave a link.
    for chip in AboutBrandChip.objects.filter(url=""):
        brand = Brand.objects.filter(name__iexact=chip.name).first()
        if brand:
            chip.url = f"/?brand={brand.slug}"
        else:
            chip.url = "/?q=" + quote(chip.name)
        chip.save(update_fields=["url"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0007_seed_about_content"),
        ("catalog", "0022_alter_product_oem_cross"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutbrandchip",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Куда ведёт плитка бренда. Напр.: /?brand=mannol",
                max_length=300,
                verbose_name="ссылка",
            ),
        ),
        migrations.RunPython(apply_tweaks, noop),
    ]
