# Generated by Django 5.0.14 on 2026-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0008_aboutbrandchip_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutbrandchip",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Логотип бренда (необязательно).",
                null=True,
                upload_to="about/brands/",
                verbose_name="логотип",
            ),
        ),
    ]
