# Generated by Django 5.0.14 on 2026-06-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["category", "order", "name"],
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order on the site (lower numbers first)."
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order on the site (lower numbers first)."
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display order within the category (lower numbers first).",
            ),
        ),
    ]
