# Generated by Django 5.0.14 on 2026-06-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_set_taxonomy_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "product model",
                "verbose_name_plural": "product models",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Volume in litres.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Weight in kg.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.modelproduct",
            ),
        ),
    ]
