# Generated by Django 5.0.14 on 2026-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_modelproduct_product_volume_product_weight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional click-through link.",
                        verbose_name="link URL",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "banner slide",
                "verbose_name_plural": "banner slides",
                "ordering": ["order", "id"],
            },
        ),
    ]
