# Generated by Django 5.0.14 on 2026-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_bannerslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Категории, доступные для этого бренда (пусто = все категории).",
                related_name="brands",
                to="catalog.category",
            ),
        ),
    ]
