# Generated by Django 5.0.14 on 2026-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_brand_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="viscosity",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Например: 5W-30, 0W-20 (только для подходящих товаров).",
                max_length=20,
            ),
        ),
    ]
