# Generated by Django 5.0.14 on 2026-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_product_viscosity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="volume_unit",
            field=models.CharField(
                blank=True,
                default="л",
                max_length=16,
                verbose_name="единица измерения объёма",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                blank=True,
                default="кг",
                max_length=16,
                verbose_name="единица измерения веса",
            ),
        ),
    ]
