# Generated by Django 5.0.14 on 2026-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_product_volume_unit_product_weight_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=22, max_digits=5, verbose_name="ставка НДС, %"
            ),
        ),
    ]
