# Generated by Django 5.0.14 on 2026-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_product_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="picture_thumb",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="products/thumbs/"
            ),
        ),
    ]
