# Generated by Django 5.0.14 on 2026-07-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_product_picture_thumb"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Показывается неавторизованным посетителям.",
                        verbose_name="цена для гостей",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Используется, если у покупателя не задан тип цены.",
                        verbose_name="по умолчанию для покупателей",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип цены",
                "verbose_name_plural": "типы цен",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.pricetype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "цена",
                "verbose_name_plural": "цены",
                "ordering": ["price_type__order"],
            },
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.UniqueConstraint(
                fields=("product", "price_type"), name="unique_product_price_type"
            ),
        ),
    ]
