# Generated by Django 5.0.14 on 2026-07-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_seed_price_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproduct",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_models",
                to="catalog.brand",
                verbose_name="бренд",
            ),
        ),
        migrations.AlterField(
            model_name="modelproduct",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="modelproduct",
            constraint=models.UniqueConstraint(
                fields=("brand", "name"), name="unique_brand_model_name"
            ),
        ),
    ]
