# Generated by Django 5.0.14 on 2026-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_backfill_model_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="viscosity",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Например: 5W30, 0W20 (только для подходящих товаров).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Объём в указанной единице измерения",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Вес в указанной единице измерения",
                max_digits=10,
                null=True,
            ),
        ),
    ]
