# Generated by Django 5.0.14 on 2026-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_product_pack_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="mahl_cross",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="кросс-номер MAHLE"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mann_cross",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="кросс-номер MANN"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sakura_cross",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="кросс-номер SAKURA"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                verbose_name="Номер производителя",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="Код 1С"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="viscosity",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Например: 5W30, 0W20 (только для подходящих товаров).",
                max_length=20,
                verbose_name="вязкость",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Объём в указанной единице измерения",
                max_digits=10,
                null=True,
                verbose_name="объём",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Вес в указанной единице измерения",
                max_digits=10,
                null=True,
                verbose_name="вес",
            ),
        ),
    ]
