# Generated by Django 5.0.14 on 2026-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_product_cross_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="knecht_cross",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="кросс-номер KNECHT"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="oem_cross",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="кросс-номер OEM"
            ),
        ),
    ]
