# Generated by Django 5.0.14 on 2026-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_product_knecht_cross_product_oem_cross"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="oem_cross",
            field=models.CharField(
                blank=True, max_length=10000, verbose_name="кросс-номер OEM"
            ),
        ),
    ]
