# Generated by Django 5.0.14 on 2026-08-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_alter_product_oem_cross"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="search_aliases",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Другие написания бренда для поиска: латиница/кириллица, транслитерация, частые опечатки. Разделяйте пробелом или запятой. Например, для «Аляska»: «аляска alaska». Покупателям не показывается.",
                verbose_name="альтернативные названия для поиска",
            ),
        ),
    ]
