# Generated by Django 5.0.14 on 2026-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_brand_search_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="certificate",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ссылка или текст. Ссылка (http…) показывается кликабельной. Можно указать вместе с загруженным файлом.",
                max_length=500,
                verbose_name="сертификат соответствия",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите файл — на странице товара появится ссылка на него.",
                null=True,
                upload_to="certificates/",
                verbose_name="файл сертификата соответствия",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="show_certificate",
            field=models.BooleanField(
                default=True, verbose_name="показывать сертификат на странице товара"
            ),
        ),
    ]
