# Generated by Django 5.0.14 on 2026-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_product_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="поставщик"
            ),
        ),
    ]
