# Generated by Django 5.0.14 on 2026-06-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Orders placed for this warehouse are emailed here.",
                max_length=254,
            ),
        ),
    ]
