# Generated by Django 5.0.14 on 2026-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0002_warehouse_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="managers/"),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ["surname", "name"],
            },
        ),
        migrations.AddField(
            model_name="warehouse",
            name="opening_hours",
            field=models.TextField(
                blank=True,
                help_text="Например: Пн–Пт 9:00–18:00, Сб 10:00–15:00, Вс выходной",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="warehouses/"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="warehouses", to="warehouses.manager"
            ),
        ),
    ]
