# Generated by Django 5.0.14 on 2026-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouses",
            "0003_manager_warehouse_opening_hours_warehouse_picture_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="position",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="должность"
            ),
        ),
    ]
