# Generated by Django 5.0.14 on 2026-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0004_manager_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={"ordering": ["order", "surname", "name"]},
        ),
        migrations.AddField(
            model_name="manager",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Меньше — выше в списке."
            ),
        ),
    ]
