# Generated by Django 5.0.14 on 2026-07-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0005_alter_manager_options_manager_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
