# Generated by Django 5.0.14 on 2026-06-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("confirmed", "Подтверждён"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
