# Generated by Django 5.0.14 on 2026-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_favorite_favorite_unique_user_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("cashless", "Безналичные")],
                default="cashless",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
