# Generated by Django 5.0.14 on 2026-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("delivery", "Доставка"), ("pickup", "Самовывоз")],
                default="delivery",
                max_length=20,
                verbose_name="способ получения",
            ),
        ),
    ]
