# Generated by Django 5.0.14 on 2026-09-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_product_certificate"),
        ("orders", "0006_order_delivery_method"),
        ("warehouses", "0006_warehouse_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата документа"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Код 1С"
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="контрагент"
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="тип контрагента"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="расход",
                    ),
                ),
                ("document", models.CharField(max_length=255, verbose_name="документ")),
                (
                    "document_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="тип документа"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сопоставляется по Коду 1С; пусто — если товара нет в каталоге.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_records",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_records",
                        to="warehouses.warehouse",
                        verbose_name="склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "продажа",
                "verbose_name_plural": "статистика продаж",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="orders_sale_date_fbb1f8_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "sku", "document"), name="unique_sale_line"
            ),
        ),
    ]
