# Generated by Django 5.0.14 on 2026-09-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_product_supplier"),
        ("orders", "0007_salesrecord_salesrecord_unique_sale_line"),
        ("warehouses", "0006_warehouse_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Код 1С"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="дата")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="остаток на конец дня",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_snapshots",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_snapshots",
                        to="warehouses.warehouse",
                        verbose_name="склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "остаток (история)",
                "verbose_name_plural": "история остатков",
                "ordering": ["sku", "warehouse", "date"],
                "indexes": [
                    models.Index(
                        fields=["warehouse", "date"],
                        name="orders_stoc_warehou_0457cf_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stocksnapshot",
            constraint=models.UniqueConstraint(
                fields=("sku", "warehouse", "date"), name="unique_stock_snapshot"
            ),
        ),
    ]
