# Generated by Django 5.0.14 on 2026-09-21 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_product_supplier"),
        ("orders", "0008_stocksnapshot_stocksnapshot_unique_stock_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(max_length=255, verbose_name="поставщик"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="срок поставки, дней"
                    ),
                ),
                (
                    "safety_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="страховой запас, дней"
                    ),
                ),
                (
                    "sales_period_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="период продаж, дней"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="примечание"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ поставщику",
                "verbose_name_plural": "заказы поставщикам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="заказать"),
                ),
                (
                    "current_stock",
                    models.IntegerField(
                        default=0, verbose_name="остаток на момент заказа"
                    ),
                ),
                (
                    "avg_daily_sales",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="продаж в день",
                    ),
                ),
                (
                    "suggested_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="рекомендовано"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-quantity", "name"],
            },
        ),
    ]
